name: Publish Python 🐍 distributions 📦 to PyPI

on:
  release:
    types:
      - published

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  build-n-publish-pypi:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    environment: production
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@eb238b55efaa70779f274895e782ed17c84f2895 # v2.6.1
        with:
          egress-policy: audit
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Python3
        uses: actions/setup-python@0a5c61591373683505ea898e09a3ea4f39ef2b9c # v5.0.0
        with:
          python-version: "3.x"
      - name: Install packaging libraries
        run: |
          python -m pip install flit
      - name: Build a binary wheel and a source tarball
        run: |
          python -m flit build
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf # v1.8.11
